apiVersion: v1
kind: Pod
metadata:
  name: test-secret-volume
spec:
  containers:
    - name: test-secret-volume
      image: busybox
      args: [ "sleep", "300" ]
      volumeMounts:
        - mountPath: /projected-volume # 该目录下会有Secret定义的user, pass多个文件
          name: my-secret-pv
          readOnly: true
      imagePullPolicy: IfNotPresent
  volumes:
    - name: my-secret-pv # pod清单文件中自定义名
      projected:
        sources:
          - secret:
              name: mysecret # 用这个secret
  restartPolicy: Always
